[package]
name = "whirlpool"
version = "0.3.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "whirlpool"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = { version = "0.30.1", features = ["metadata", "memo"] }
spl-token = { version = "4", features = ["no-entrypoint"] }
spl-transfer-hook-interface = "0.6.5"
solana-program = "1.18.18"
thiserror = "1.0"
uint = { version = "0.9.1", default-features = false }
borsh09 = { package = "borsh", version = "0.9.1" }

[dev-dependencies]
proptest = "1.0"
serde = "1.0.117"
serde_json = "1.0.59"

[dev-dependencies.serde_with]
version = "1.12.0"
features = ["json"]

[patch.crates-io]
anchor-lang = { git = "https://github.com/coral-xyz/anchor", tag = "v0.30.1" }
